/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiarsipsuratv2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Timer;

/**
 *
 * @author dimas
 */
public final class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    
    Statement st;
    ResultSet rs;
    koneksi koneksi;
    Timer t;
    
    String user_id = UserSession.getU_uid();
    int id_level = UserSession.getId_level();
    String UserMenu = String.valueOf(id_level);
    
    public FormUtama() {
        koneksi = new koneksi();
        initComponents();
        
        switch(UserMenu) {
            case  "1":
                MenuManager();
                break;
            case "2":
                MenuStaff();
                break;
            case "3":
                MenuAdmin();
                break;
        }
    }
    
    public void MenuManager() {
        // hanya diblokir, tetapi menu item tetap muncul
        //jMenuItemSuratMasuk.setEnabled(false);
        //jMenuItemSuratKeluar.setEnabled(false);
        
        jMenuItemManajemenUser.setVisible(true);
        jMenuItemSuratMasuk.setVisible(false);
        jMenuItemSuratKeluar.setVisible(false);
    }
    
    public void MenuStaff() {
        jMenuItemManajemenUser.setVisible(false);
        
    }
    
    public void MenuAdmin() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemManajemenUser = new javax.swing.JMenuItem();
        jMenuItemGantiPassword = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuArsip = new javax.swing.JMenu();
        jMenuItemSuratMasuk = new javax.swing.JMenuItem();
        jMenuItemSuratKeluar = new javax.swing.JMenuItem();
        jMenuItemDisposisi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aplikasi Arsip Surat");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI APLIKASI ARSIP SURAT");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FOLDER.PNG"))); // NOI18N

        jMenuFile.setText("File");

        jMenuItemManajemenUser.setText("Manajemen User");
        jMenuFile.add(jMenuItemManajemenUser);

        jMenuItemGantiPassword.setText("Ganti Password");
        jMenuFile.add(jMenuItemGantiPassword);
        jMenuFile.add(jSeparator1);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogout);

        jMenuBar1.add(jMenuFile);

        jMenuArsip.setText("Arsip");

        jMenuItemSuratMasuk.setText("Surat Masuk");
        jMenuItemSuratMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSuratMasukActionPerformed(evt);
            }
        });
        jMenuArsip.add(jMenuItemSuratMasuk);

        jMenuItemSuratKeluar.setText("Surat Keluar");
        jMenuArsip.add(jMenuItemSuratKeluar);

        jMenuItemDisposisi.setText("Disposisi");
        jMenuArsip.add(jMenuItemDisposisi);

        jMenuBar1.add(jMenuArsip);

        jMenu1.setText("Laporan");

        jMenuItem1.setText("Laporan Surat Masuk");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Laporan Surat Keluar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        int Logout = JOptionPane.showOptionDialog(this, "Logout dari Aplikasi ?", 
                "Pesan Logout", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if (Logout == JOptionPane.YES_OPTION) {
            new FormLogin().show();
            this.dispose(); // Keluar dari Aplikasi
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        
        new FormAbout().setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemSuratMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSuratMasukActionPerformed
        // TODO add your handling code here:
        
        new FormSuratMasuk().show();
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemSuratMasukActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        
         int close = JOptionPane.showOptionDialog(this, "Logout dari Aplikasi ?", 
                "Pesan Logout", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if (close == JOptionPane.YES_OPTION) {
            new FormLogin().show();
            this.dispose(); // Keluar dari Aplikasi
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
        userInteraction();
        
    }//GEN-LAST:event_formMouseMoved

    
    // ---------- Automatic Logout System ----------
    public void logout() {
        this.setVisible(false);
        new FormLogin().setVisible(true);
        stopTimer();
    }
    
    public void session() {
        stopTimer();
        t = new Timer(600000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logout();
            }
        });
        t.start();
    }
    
    public void stopTimer() {
        if (t != null) {
            t.stop();
        }
    }
    
    public void userInteraction() {
        session();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormUtama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArsip;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemDisposisi;
    private javax.swing.JMenuItem jMenuItemGantiPassword;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemManajemenUser;
    private javax.swing.JMenuItem jMenuItemSuratKeluar;
    private javax.swing.JMenuItem jMenuItemSuratMasuk;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
