/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dapproduction.desktop.application.panel;

import com.dapproduction.desktop.application.dialog.DialogBarang;
import com.dapproduction.desktop.entity.Barang;
import com.dapproduction.desktop.service.DatabaseHelper;
import com.dapproduction.desktop.service.BarangService;
import com.stripbandunk.jwidget.model.DefaultPaginationModel;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author dimas
 */
public class PanelBarang extends javax.swing.JPanel {

    private DynamicTableModel<Barang> tableModel;
    private final int PAGE_SIZE = 5;
    /**
     * Creates new form PanelBarang
     */
    public PanelBarang() {
        initComponents();
        
        tableModel = new DynamicTableModel<>(Barang.class);
        jDynamicTable1.setDynamicModel(tableModel);
    }
    
    public void reload() {
        
        new SwingWorker<List<Barang>, Object>() {
            @Override
            protected List<Barang> doInBackground() throws Exception {
                BarangService service = DatabaseHelper.getBarangService();
                List<Barang> select = service.select(0, PAGE_SIZE);
                return select;
            }

            @Override
            protected void done() {
                try {
                    // reload data pertama kali
                    BarangService service = DatabaseHelper.getBarangService();
                    int totalItem = new Long(service.count()).intValue();
                    
                    DefaultPaginationModel paginationModel = new DefaultPaginationModel(PAGE_SIZE, totalItem);
                    jPagination1.setModel(paginationModel);
                    
                    tableModel.clear();
                    for (Barang barang : get()) {
                        tableModel.add(barang);
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(PanelBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }        
        }.execute();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDynamicTable1 = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination1 = new com.stripbandunk.jwidget.JPagination();
        cRUDPanel1 = new com.stripbandunk.component.CRUDPanel();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Manajemen Barang");

        jScrollPane1.setViewportView(jDynamicTable1);

        jPagination1.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPagination1OnPageChange(evt);
            }
        });

        cRUDPanel1.addCRUDListener(new com.stripbandunk.component.CRUDListener() {
            public void onDelete(com.stripbandunk.component.CRUDEvent evt) {
                cRUDPanel1OnDelete(evt);
            }
            public void onInsert(com.stripbandunk.component.CRUDEvent evt) {
                cRUDPanel1OnInsert(evt);
            }
            public void onReload(com.stripbandunk.component.CRUDEvent evt) {
                cRUDPanel1OnReload(evt);
            }
            public void onUpdate(com.stripbandunk.component.CRUDEvent evt) {
                cRUDPanel1OnUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cRUDPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPagination1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cRUDPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPagination1OnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPagination1OnPageChange
        // TODO add your handling code here:
        
        final int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        final int max = evt.getPageSize();
        
        new SwingWorker<List<Barang>, Object>(){
            @Override
            protected List<Barang> doInBackground() throws Exception {
                BarangService service = DatabaseHelper.getBarangService();
                List<Barang> select = service.select(skip, max);
                return select;
            }

            @Override
            protected void done() {
                try {
                    tableModel.clear();
                    for (Barang barang : get()) {
                        tableModel.add(barang);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(PanelBarang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(PanelBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.execute();
    }//GEN-LAST:event_jPagination1OnPageChange

    private void cRUDPanel1OnReload(com.stripbandunk.component.CRUDEvent evt) {//GEN-FIRST:event_cRUDPanel1OnReload
        // TODO add your handling code here:
        
        reload();
        
    }//GEN-LAST:event_cRUDPanel1OnReload

    private void cRUDPanel1OnInsert(com.stripbandunk.component.CRUDEvent evt) {//GEN-FIRST:event_cRUDPanel1OnInsert
        // TODO add your handling code here:
        
        DialogBarang dialog = new DialogBarang();
        dialog.setLocationRelativeTo(this);
        Barang barang = dialog.tambah();
        
        if (barang != null) {
            BarangService service = DatabaseHelper.getBarangService();
            service.insert(barang);
            
            reload();
        }
    }//GEN-LAST:event_cRUDPanel1OnInsert

    private void cRUDPanel1OnUpdate(com.stripbandunk.component.CRUDEvent evt) {//GEN-FIRST:event_cRUDPanel1OnUpdate
        // TODO add your handling code here:
        
        if (jDynamicTable1.getSelectedRow() != 1) {
            Barang barang = tableModel.get(jDynamicTable1.convertRowIndexToModel(jDynamicTable1.getSelectedRow()));
            DialogBarang dialog = new DialogBarang();
            dialog.setLocationRelativeTo(this);
            
            Barang hasil = dialog.ubah(barang);
            if (hasil != null) {
                BarangService service = DatabaseHelper.getBarangService();
                service.update(barang);
                
                reload();
            }
        }
    }//GEN-LAST:event_cRUDPanel1OnUpdate

    private void cRUDPanel1OnDelete(com.stripbandunk.component.CRUDEvent evt) {//GEN-FIRST:event_cRUDPanel1OnDelete
        // TODO add your handling code here:
        
        if (jDynamicTable1.getSelectedRow() != 1) {
            if (JOptionPane.showConfirmDialog(this, 
                    "Anda Yakin?", "Hapus Barang", JOptionPane.OK_CANCEL_OPTION)
                    == JOptionPane.OK_OPTION) {
                Barang barang = tableModel.get(jDynamicTable1.convertRowIndexToModel(jDynamicTable1.getSelectedRow()));
                BarangService service = DatabaseHelper.getBarangService();
                service.delete(barang);
                
                reload();
            }
        }
    }//GEN-LAST:event_cRUDPanel1OnDelete


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stripbandunk.component.CRUDPanel cRUDPanel1;
    private com.stripbandunk.jwidget.JDynamicTable jDynamicTable1;
    private javax.swing.JLabel jLabel1;
    private com.stripbandunk.jwidget.JPagination jPagination1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
