/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilnama;

import java.awt.Color;

/**
 *
 * @author dimas
 */
public class Identitas extends javax.swing.JFrame {

    /**
     * Creates new form Identitas
     */
    public Identitas() {
        initComponents();
        hilang();
    }
    
    public void hilang() {
        jLabelNama.setVisible(false);
        jLabelAlamat.setVisible(false);
        jLabelNoHp.setVisible(false);
    }
    
    public void muncul() {
        jLabelNama.setVisible(true);
        jLabelAlamat.setVisible(true);
        jLabelNoHp.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNama = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jLabelNoHp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMerah = new javax.swing.JButton();
        jButtonBiru = new javax.swing.JButton();
        jButtonHijau = new javax.swing.JButton();
        jButtonCampur = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonHilang = new javax.swing.JButton();
        jButtonTampil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(248, 300));
        setMinimumSize(new java.awt.Dimension(248, 300));

        jLabelNama.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelNama.setText("Nama      :");

        jLabelAlamat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelAlamat.setText("Alamat    :");

        jLabelNoHp.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelNoHp.setText("No Hp     :");

        jButtonMerah.setText("Merah");
        jButtonMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMerahActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMerah);

        jButtonBiru.setText("Biru");
        jButtonBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiruActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBiru);

        jButtonHijau.setText("Hijau");
        jButtonHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHijauActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHijau);

        jButtonCampur.setText("Campur");
        jButtonCampur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCampurActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCampur);

        jButtonHilang.setText("Hilang");
        jButtonHilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHilangActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHilang);

        jButtonTampil.setText("Tampilkan");
        jButtonTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTampilActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTampil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAlamat)
                                    .addComponent(jLabelNoHp))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabelNama)
                .addGap(18, 18, 18)
                .addComponent(jLabelAlamat)
                .addGap(18, 18, 18)
                .addComponent(jLabelNoHp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTampilActionPerformed
        // TODO add your handling code here:
        
        jLabelNama.setText  ("Nama      : Hamdan Wadi");
        jLabelAlamat.setText("Alamat    : Turida Barat");
        jLabelNoHp.setText  ("No Hp     : 08786420073");
        
        muncul();
        
    }//GEN-LAST:event_jButtonTampilActionPerformed

    private void jButtonMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMerahActionPerformed
        // TODO add your handling code here:
        
        jLabelNama.setForeground(Color.red);
        jLabelAlamat.setForeground(Color.red);
        jLabelNoHp.setForeground(Color.red);
        
    }//GEN-LAST:event_jButtonMerahActionPerformed

    private void jButtonBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiruActionPerformed
        // TODO add your handling code here:
        
        jLabelNama.setForeground(Color.blue);
        jLabelAlamat.setForeground(Color.blue);
        jLabelNoHp.setForeground(Color.blue);
        
    }//GEN-LAST:event_jButtonBiruActionPerformed

    private void jButtonHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHijauActionPerformed
        // TODO add your handling code here:
        
        jLabelNama.setForeground(Color.green);
        jLabelAlamat.setForeground(Color.green);
        jLabelNoHp.setForeground(Color.green);
        
    }//GEN-LAST:event_jButtonHijauActionPerformed

    private void jButtonCampurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCampurActionPerformed
        // TODO add your handling code here:
        
        
        jLabelNama.setForeground(Color.red);
        jLabelAlamat.setForeground(Color.blue);
        jLabelNoHp.setForeground(Color.green);
        
        
    }//GEN-LAST:event_jButtonCampurActionPerformed

    private void jButtonHilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHilangActionPerformed
        // TODO add your handling code here:
        
        hilang();
        
    }//GEN-LAST:event_jButtonHilangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Identitas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBiru;
    private javax.swing.JButton jButtonCampur;
    private javax.swing.JButton jButtonHijau;
    private javax.swing.JButton jButtonHilang;
    private javax.swing.JButton jButtonMerah;
    private javax.swing.JButton jButtonTampil;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNoHp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
